language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
env:
 - CFFI=no
 - CFFI=yes
matrix:
 exclude:
 - python: pypy
   env: CFFI=no
 - python: pypy3
   env: CFFI=no
 include:
 - python: 2.6
   env: CFFI=no
   dist: trusty
 - python: pypy
   env: CFFI=yes
 - python: pypy3
   env: CFFI=yes
 - language: c
   script: cd src/test && make
   after_success: true
 - language: c
   dist: trusty
   install: sudo apt-get install libc6-dev-i386
   script: cd src/test && CFLAGS="-m32" UNDEFS="-UHAVE_UINT128" make
   after_success: true
 - language: c
   script: cd src/test && CPPFLAGS="-DHAVE_X86INTRIN_H" make
   after_success: true
 - python: 3.8
   install: pip install mypy
   script: mypy lib/
   after_success: true
 - os: osx
   env: PYCRYPTODOME_DEBUG=1
   env: CFLAGS=" -isysroot $(xcrun --sdk macosx --show-sdk-path)"
   language: generic
   install: pip2 install cibuildwheel==1.1.0
   after_success: travis/travis_after_success_osx.sh
services:
 - docker
branches:
  except:
  - "/^.*-wip$/"
install:
- travis/travis_install.sh
script:
- travis/travis_script.sh
after_success:
- travis/travis_after_success.sh
deploy:
  provider: s3
  access_key_id: AKIAISG4H2IJZLISXOPQ
  secret_access_key:
    secure: DAuc3n+JLxlBmCLgQuLSXwIRHropTVK/TWj3jD99aB1+Bzy5CpmPtXyR3DGltGF2Bum52xcRM8dLFktinFkMqKF7UKZRGNwEey07Nhen94AGjkLomeEM0SRRjVP6T8RqLBK+buNcoRqiFTNM+JlW5ndY6Wy+kFaan+qk3UNz570=
  bucket: pycryptodome-releases
  local_dir: wheelhouse
  skip_cleanup: true
  acl: public_read
  on:
    condition: -d wheelhouse
    all_branches: true
    repo: Legrandin/pycryptodome
    tags: true
